<?php

namespace App\Repository;

use Psr\Container\ContainerInterface;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BreedRepository extends Repository 
{
    /**
     * Retorna um array com as raças de gato encontradas no banco de dados pelo nome
     *
     * @param ContainerInterface $container
     * @param string $name
     * @return array
     */
    public function getBreedsByName(ContainerInterface $container, string $name) : array
    {
        $filterName = $container->utilService->antiInjection($name);

        $select = ' SELECT * ';        
        $from = ' FROM breed AS B ';
        $where = " WHERE B.breed_name like '%{$filterName}%' ";        
        $orderBy = ' ORDER BY B.breed_name ';        
        $sql = $select . $from . $where . $orderBy;        

        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $stmt->execute();
        return $stmt->fetchAllAssociative();
    }
}