CREATE TABLE IF NOT EXISTS token(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	token VARCHAR(1000) UNIQUE NOT NULL,
	refresh_token VARCHAR(1000) NOT NULL,
	expired_at DATETIME NOT NULL,
	active TINYINT NOT NULL DEFAULT 1,
	user_id INT NOT NULL,
	FOREIGN KEY (user_id) REFERENCES user(id)
);